name: Generate Docs

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate TypeDoc
        run: npm run docs

      - name: Checkout docs-repo
        uses: actions/checkout@v3
        with:
          repository: rage-js/docs
          token: ${{ secrets.PAT_TOKEN }}
          path: rage-js-docs
          ref: docs

      - name: Copy docs to rage-js-docs
        run: |
          rm -rf rage-js-docs/docs/core
          mv docs core
          cp -R core rage-js-docs/docs

      - name: Log last docs update
        run: |
          touch rage-js-docs/last-update.txt
          echo "Last update on docs: $(date "+%Y-%m-%d %H:%M:%S")" >> rage-js-docs/last-update.txt

      - name: Commit and push changes to rage-js-docs
        run: |
          cd rage-js-docs
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "Github Actions"
          git add .
          git commit -m "Update docs"
          git push origin docs --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
